config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :open_positions

  resources :positions

  devise_for :users

  get 'logout_path', :to => 'devise/sessions#destroy', :as => :logout

  root 'landing#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/open_position.rb
class OpenPosition < ActiveRecord::Base
  validates :position, presence: true

  belongs_to :position

end

app/models/position.rb
class Position < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true

  belongs_to :user
  belongs_to :admin_user
  has_many :open_positions
end

app/models/user.rb
class User < ActiveRecord::Base
  # before_action :authenticate_user!
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/api/v1/open_positions_controller.rb
class API::V1::OpenPositionsController < ApplicationController

  respond to :json

  def index
    @open_positions = OpenPosition.all
  end

  def show
    @open_positions = OpenPosition.find(params[:id])
  end
end

app/controllers/api/v1/registrations_controller.rb
# class Api::RegistrationsController < Api::BaseController
#
#   respond_to :json
#   def create
#
#     user = User.new(params[:user])
#     if user.save
#       render json: user.as_json(auth_token: user.authentication_token, email: user.email), status: 201 #Created
#       return
#     else
#       warden.custom_failure!
#       render json: user.errors, status: 422 #unprocessable Entity
#     end
#   end
# end

app/controllers/api/v1/sessions_controller.rb
# class Api::SessionsController < Api::BaseController
#   prepend_before_filter :require_no_authentication, :only => [:create ]
#   # include Devise::Controllers
#
#   before_filter :ensure_params_exist
#
#   respond_to :json
#
#   def create
#     build_resource
#     resource = User.find_for_database_authentication(login: params[:user_login][:login])
#     return invalid_login_attempt unless resource
#
#     if resource.valid_password?(params[:user_login][:password])
#       sign_in("user", resource)
#       render json: {success: true, auth_token: resource.authentication_token, login: resource.login, email: resource.email}
#       return
#     end
#     invalid_login_attempt
#   end
#
#   def destroy
#     sign_out(resource_name)
#   end
#
#   protected
#   def ensure_params_exist
#     return unless params[:user_login].blank? #.blank made more sense than .empty
#     render json: {success: false, message: "missing user_login"}, status: 422
#   end
#
#   def invalid_login_attempt
#     warden.custom_failure!
#     render json: {:success=>false, message: "Error with your username or password"}, status: 401
#   end
# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index

  end
end

app/controllers/open_positions_controller.rb
class OpenPositionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_open_position, only: [:show, :edit, :update, :destroy]


  # GET /open_positions
  # GET /open_positions.json
  def index
    @open_positions = OpenPosition.all
  end

  # GET /open_positions/1
  # GET /open_positions/1.json
  def show
  end

  # GET /open_positions/new
  def new
    @open_position = OpenPosition.new
  end

  # GET /open_positions/1/edit
  def edit
  end

  # POST /open_positions
  # POST /open_positions.json
  def create
    @open_position = OpenPosition.new(open_position_params)

    respond_to do |format|
      if @open_position.save
        format.html { redirect_to @open_position, notice: 'Open position was successfully created.' }
        format.json { render :show, status: :created, location: @open_position }
      else
        format.html { render :new }
        format.json { render json: @open_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /open_positions/1
  # PATCH/PUT /open_positions/1.json
  def update
    respond_to do |format|
      if @open_position.update(open_position_params)
        format.html { redirect_to @open_position, notice: 'Open position was successfully updated.' }
        format.json { render :show, status: :ok, location: @open_position }
      else
        format.html { render :edit }
        format.json { render json: @open_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /open_positions/1
  # DELETE /open_positions/1.json
  def destroy
    @open_position.destroy
    respond_to do |format|
      format.html { redirect_to open_positions_url, notice: 'Open position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_open_position
      @open_position = OpenPosition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def open_position_params
      params.require(:open_position).permit(:open_position, :details, :interest)
    end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url, notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_params
      params.require(:position).permit(:position, :status, :name, :email, :phone )
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/open_positions_helper.rb
module OpenPositionsHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/application/_top_bar.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href= "/open_positions">voluntee</a></h1>
    </li>
     <!--Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone-->
    <!--<li class="toggle-topbar menu-icon"><a href=""><span>Menu</span></a></li>-->
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><a href="#" class="button [radius round]">profile</a></li>
      <!--<li class="has-dropdown">-->
        <!--<a href="#">Right Button Dropdown</a>-->
        <!--<ul class="dropdown">-->
          <!--<li><a href="#">First link in dropdown</a></li>-->
        </ul>
      </li>
    </ul>

     Left Nav Section
    <ul class="left">
      <li><%= link_to "sign_out", destroy_user_session_path, :method => :delete %></li>
    </ul>
  </section>
</nav>

app/views/landing/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facebook Login JavaScript Example</title>
  <meta charset="UTF-8">
</head>
<body>
<script>
    // This is called with the results from from FB.getLoginStatus().
    function statusChangeCallback(response) {
        console.log('statusChangeCallback');
        console.log(response);
        // The response object is returned with a status field that lets the
        // app know the current login status of the person.
        // Full docs on the response object can be found in the documentation
        // for FB.getLoginStatus().
        if (response.status === 'connected') {
            // Logged into your app and Facebook.
            testAPI();
        } else if (response.status === 'not_authorized') {
            // The person is logged into Facebook, but not your app.
            document.getElementById('status').innerHTML = 'Please log ' +
                    'into this app.';
        } else {
            // The person is not logged into Facebook, so we're not sure if
            // they are logged into this app or not.
            document.getElementById('status').innerHTML = 'Please log ' +
                    'into Facebook.';
        }
    }

    // This function is called when someone finishes with the Login
    // Button.  See the onlogin handler attached to it in the sample
    // code below.
    function checkLoginState() {
        FB.getLoginStatus(function(response) {
            statusChangeCallback(response);
        });
    }

    window.fbAsyncInit = function() {
        FB.init({
            appId      : '479299915547939',
            cookie     : true,  // enable cookies to allow the server to access
            // the session
            xfbml      : true,  // parse social plugins on this page
            version    : 'v2.0' // use version 2.0
        });

        // Now that we've initialized the JavaScript SDK, we call
        // FB.getLoginStatus().  This function gets the state of the
        // person visiting this page and can return one of three states to
        // the callback you provide.  They can be:
        //
        // 1. Logged into your app ('connected')
        // 2. Logged into Facebook, but not your app ('not_authorized')
        // 3. Not logged into Facebook and can't tell if they are logged into
        //    your app or not.
        //
        // These three cases are handled in the callback function.

        FB.getLoginStatus(function(response) {
            statusChangeCallback(response);
        });

    };

    // Load the SDK asynchronously
    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

    // Here we run a very simple test of the Graph API after login is
    // successful.  See statusChangeCallback() for when this call is made.
    function testAPI() {
        console.log('Welcome!  Fetching your information.... ');
        FB.api('/me', function(response) {
            console.log('Successful login for: ' + response.name);
            document.getElementById('status').innerHTML =
                    'Thanks for logging in, ' + response.name + '!';
        });
    }
</script>

<!--
  Below we include the Login Button social plugin. This button uses
  the JavaScript SDK to present a graphical Login button that triggers
  the FB.login() function when clicked.
-->

<fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
</fb:login-button>

<div id="status">
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <%= render 'top_bar' %>
  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/open_positions/_form.html.erb
<%= form_for(@open_position) do |f| %>
  <% if @open_position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@open_position.errors.count, "error") %> prohibited this open_position from being saved:</h2>

      <ul>
      <% @open_position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :open_position %><br>
    <%= f.text_field :open_position %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_field :details %>
  </div>
  <div class="field">
    <%= f.label :interest %><br>
    <%= f.check_box :interest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/open_positions/edit.html.erb
<h1>Editing open_position</h1>

<%= render 'form' %>

<%= link_to 'Show', @open_position %> |
<%= link_to 'Back', open_positions_path %>

app/views/open_positions/index.html.erb
<h1>Listing open_positions</h1>

<table>
  <thead>
    <tr>
      <th>Open position</th>
      <th>Details</th>
      <th>Interest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @open_positions.each do |open_position| %>
      <tr>
        <td><%= open_position.open_position %></td>
        <td><%= open_position.details %></td>
        <td><%= open_position.interest %></td>
        <td><%= link_to 'Show', open_position %></td>
        <td><%= link_to 'Edit', edit_open_position_path(open_position) %></td>
        <td><%= link_to 'Destroy', open_position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Open position', new_open_position_path %>

app/views/open_positions/new.html.erb
<h1>New open_position</h1>

<%= render 'form' %>

<%= link_to 'Back', open_positions_path %>

app/views/open_positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Open position:</strong>
  <%= @open_position.open_position %>
</p>

<p>
  <strong>Details:</strong>
  <%= @open_position.details %>
</p>

<p>
  <strong>Interest:</strong>
  <%= @open_position.interest %>
</p>

<%= link_to 'Edit', edit_open_position_path(@open_position) %> |
<%= link_to 'Back', open_positions_path %>

app/views/positions/_form.html.erb
<%= form_for(@position) do |f| %>
  <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% @position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing position</h1>

<%= render 'form' %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<h1>Listing positions</h1>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>Status</th>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= position.position %></td>
        <td><%= position.status %></td>
        <td><%= position.name %></td>
        <td><%= position.email %></td>
        <td><%= position.phone %></td>
        <td><%= link_to 'Show', position %></td>
        <td><%= link_to 'Edit', edit_position_path(position) %></td>
        <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<h1>New position</h1>

<%= render 'form' %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position:</strong>
  <%= @position.position %>
</p>

<p>
  <strong>Status:</strong>
  <%= @position.status %>
</p>

<p>
  <strong>Name:</strong>
  <%= @position.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @position.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @position.phone %>
</p>

<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>